<a href="https://colab.research.google.com/github/lokeshudalkar/Python_Pandas/blob/main/DataScience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Python Pandas**

In [1]:
import pandas as pd

In [2]:
#Read csv file
df = pd.read_csv("/content/Salaries.csv")

In [3]:
df.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [4]:
df.tail()

         rank discipline  phd  service     sex  salary
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [5]:
print("Maximum salary is" , df.salary.max())

Maximum salary is 186960

In [6]:
print("Maximum salary is" , df.salary.min())

Maximum salary is 57800

In [7]:
df.head(51)

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
12   AsstProf          B    1        0    Male   88000
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
20   AsstProf          B    4        4    Male   92000
21       Prof          A   33       30    Male  103106
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
28   AsstProf          B    7        2    Male   91300
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
37       Prof          A   20        8    Male  102000
38   AsstProf          B    4        3    Male   91000
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
50   AsstProf          B   10        5  Female   97032

In [8]:
print("Maximum salary is" , df.sort_values(by = 'salary'))

Maximum salary is          rank discipline  phd  service     sex  salary
9        Prof          A   51       51    Male   57800
54  AssocProf          A   25       22  Female   62884
66   AsstProf          A    7        6  Female   63100
71  AssocProf          B   12        9  Female   71065
55   AsstProf          A    2        0  Female   72500
..        ...        ...  ...      ...     ...     ...
31       Prof          B   22       21    Male  155750
27       Prof          A   45       43    Male  155865
72       Prof          B   24       15  Female  161101
13       Prof          B   35       33    Male  162200
0        Prof          B   56       49    Male  186960

[78 rows x 6 columns]

In [9]:
df.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [10]:
df.size

468

In [11]:
df.iloc[40]

rank            Prof
discipline         A
phd               39
service           36
sex           Female
salary        137000
Name: 40, dtype: object

In [12]:
df.ndim

2

In [13]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [14]:
df.shape

(78, 6)

In [15]:
df.values

array([['Prof', 'B', 56, 49, 'Male', 186960],
       ['Prof', 'A', 12, 6, 'Male', 93000],
       ['Prof', 'A', 23, 20, 'Male', 110515],
       ['Prof', 'A', 40, 31, 'Male', 131205],
       ['Prof', 'B', 20, 18, 'Male', 104800],
       ['Prof', 'A', 20, 20, 'Male', 122400],
       ['AssocProf', 'A', 20, 17, 'Male', 81285],
       ['Prof', 'A', 18, 18, 'Male', 126300],
       ['Prof', 'A', 29, 19, 'Male', 94350],
       ['Prof', 'A', 51, 51, 'Male', 57800],
       ['Prof', 'B', 39, 33, 'Male', 128250],
       ['Prof', 'B', 23, 23, 'Male', 134778],
       ['AsstProf', 'B', 1, 0, 'Male', 88000],
       ['Prof', 'B', 35, 33, 'Male', 162200],
       ['Prof', 'B', 25, 19, 'Male', 153750],
       ['Prof', 'B', 17, 3, 'Male', 150480],
       ['AsstProf', 'B', 8, 3, 'Male', 75044],
       ['AsstProf', 'B', 4, 0, 'Male', 92000],
       ['Prof', 'A', 19, 7, 'Male', 107300],
       ['Prof', 'A', 29, 27, 'Male', 150500],
       ['AsstProf', 'B', 4, 4, 'Male', 92000],
       ['Prof', 'A', 33, 30, 'Male', 103106],
       ['AsstProf', 'A', 4, 2, 'Male', 73000],
       ['AsstProf', 'A', 2, 0, 'Male', 85000],
       ['Prof', 'A', 30, 23, 'Male', 91100],
       ['Prof', 'B', 35, 31, 'Male', 99418],
       ['Prof', 'A', 38, 19, 'Male', 148750],
       ['Prof', 'A', 45, 43, 'Male', 155865],
       ['AsstProf', 'B', 7, 2, 'Male', 91300],
       ['Prof', 'B', 21, 20, 'Male', 123683],
       ['AssocProf', 'B', 9, 7, 'Male', 107008],
       ['Prof', 'B', 22, 21, 'Male', 155750],
       ['Prof', 'A', 27, 19, 'Male', 103275],
       ['Prof', 'B', 18, 18, 'Male', 120000],
       ['AssocProf', 'B', 12, 8, 'Male', 119800],
       ['Prof', 'B', 28, 23, 'Male', 126933],
       ['Prof', 'B', 45, 45, 'Male', 146856],
       ['Prof', 'A', 20, 8, 'Male', 102000],
       ['AsstProf', 'B', 4, 3, 'Male', 91000],
       ['Prof', 'B', 18, 18, 'Female', 129000],
       ['Prof', 'A', 39, 36, 'Female', 137000],
       ['AssocProf', 'A', 13, 8, 'Female', 74830],
       ['AsstProf', 'B', 4, 2, 'Female', 80225],
       ['AsstProf', 'B', 5, 0, 'Female', 77000],
       ['Prof', 'B', 23, 19, 'Female', 151768],
       ['Prof', 'B', 25, 25, 'Female', 140096],
       ['AsstProf', 'B', 11, 3, 'Female', 74692],
       ['AssocProf', 'B', 11, 11, 'Female', 103613],
       ['Prof', 'B', 17, 17, 'Female', 111512],
       ['Prof', 'B', 17, 18, 'Female', 122960],
       ['AsstProf', 'B', 10, 5, 'Female', 97032],
       ['Prof', 'B', 20, 14, 'Female', 127512],
       ['Prof', 'A', 12, 0, 'Female', 105000],
       ['AsstProf', 'A', 5, 3, 'Female', 73500],
       ['AssocProf', 'A', 25, 22, 'Female', 62884],
       ['AsstProf', 'A', 2, 0, 'Female', 72500],
       ['AssocProf', 'A', 10, 8, 'Female', 77500],
       ['AsstProf', 'A', 3, 1, 'Female', 72500],
       ['Prof', 'B', 36, 26, 'Female', 144651],
       ['AssocProf', 'B', 12, 10, 'Female', 103994],
       ['AsstProf', 'B', 3, 3, 'Female', 92000],
       ['AssocProf', 'B', 13, 10, 'Female', 103750],
       ['AssocProf', 'B', 14, 7, 'Female', 109650],
       ['Prof', 'A', 29, 27, 'Female', 91000],
       ['AssocProf', 'A', 26, 24, 'Female', 73300],
       ['Prof', 'A', 36, 19, 'Female', 117555],
       ['AsstProf', 'A', 7, 6, 'Female', 63100],
       ['Prof', 'A', 17, 11, 'Female', 90450],
       ['AsstProf', 'A', 4, 2, 'Female', 77500],
       ['Prof', 'A', 28, 7, 'Female', 116450],
       ['AsstProf', 'A', 8, 3, 'Female', 78500],
       ['AssocProf', 'B', 12, 9, 'Female', 71065],
       ['Prof', 'B', 24, 15, 'Female', 161101],
       ['Prof', 'B', 18, 10, 'Female', 105450],
       ['AssocProf', 'B', 19, 6, 'Female', 104542],
       ['Prof', 'B', 17, 17, 'Female', 124312],
       ['Prof', 'A', 28, 14, 'Female', 109954],
       ['Prof', 'A', 23, 15, 'Female', 109646]], dtype=object)

In [16]:
df.axes

[RangeIndex(start=0, stop=78, step=1),
 Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')]

In [17]:
num = len(df)
print(num)
print(len(df))

78
78

In [18]:
num_rows = df.shape[0]
print(num_rows)

78

In [19]:
df.salary.describe()

count        78.000000
mean     108023.782051
std       28293.661022
min       57800.000000
25%       88612.500000
50%      104671.000000
75%      126774.750000
max      186960.000000
Name: salary, dtype: float64

In [20]:
df.head(5)

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [21]:
df.describe()

             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [22]:
print(len(df))

78

In [23]:
df1 = df.sample(50)

In [24]:
df1

         rank discipline  phd  service     sex  salary
63       Prof          A   29       27  Female   91000
75       Prof          B   17       17  Female  124312
38   AsstProf          B    4        3    Male   91000
40       Prof          A   39       36  Female  137000
62  AssocProf          B   14        7  Female  109650
26       Prof          A   38       19    Male  148750
39       Prof          B   18       18  Female  129000
41  AssocProf          A   13        8  Female   74830
37       Prof          A   20        8    Male  102000
23   AsstProf          A    2        0    Male   85000
15       Prof          B   17        3    Male  150480
5        Prof          A   20       20    Male  122400
59  AssocProf          B   12       10  Female  103994
22   AsstProf          A    4        2    Male   73000
32       Prof          A   27       19    Male  103275
11       Prof          B   23       23    Male  134778
50   AsstProf          B   10        5  Female   97032
43   AsstProf          B    5        0  Female   77000
28   AsstProf          B    7        2    Male   91300
12   AsstProf          B    1        0    Male   88000
14       Prof          B   25       19    Male  153750
16   AsstProf          B    8        3    Male   75044
21       Prof          A   33       30    Male  103106
1        Prof          A   12        6    Male   93000
0        Prof          B   56       49    Male  186960
36       Prof          B   45       45    Male  146856
47  AssocProf          B   11       11  Female  103613
31       Prof          B   22       21    Male  155750
19       Prof          A   29       27    Male  150500
64  AssocProf          A   26       24  Female   73300
52       Prof          A   12        0  Female  105000
27       Prof          A   45       43    Male  155865
2        Prof          A   23       20    Male  110515
25       Prof          B   35       31    Male   99418
65       Prof          A   36       19  Female  117555
56  AssocProf          A   10        8  Female   77500
67       Prof          A   17       11  Female   90450
45       Prof          B   25       25  Female  140096
73       Prof          B   18       10  Female  105450
30  AssocProf          B    9        7    Male  107008
33       Prof          B   18       18    Male  120000
69       Prof          A   28        7  Female  116450
53   AsstProf          A    5        3  Female   73500
57   AsstProf          A    3        1  Female   72500
61  AssocProf          B   13       10  Female  103750
74  AssocProf          B   19        6  Female  104542
7        Prof          A   18       18    Male  126300
58       Prof          B   36       26  Female  144651
46   AsstProf          B   11        3  Female   74692
18       Prof          A   19        7    Male  107300

In [25]:
df1.describe()

             phd    service         salary
count  50.000000  50.000000      50.000000
mean   19.740000  14.700000  110564.440000
std    12.470062  12.387041   27698.009275
min     1.000000   0.000000   72500.000000
25%    11.000000   5.250000   91000.000000
50%    18.000000  10.500000  104771.000000
75%    26.750000  20.750000  128325.000000
max    56.000000  49.000000  186960.000000

In [26]:
df.salary.std()
df.select_dtypes(include=['number']).std()

phd           12.498425
service       12.139768
salary     28293.661022
dtype: float64

In [27]:
df2 = df.head(50)
#df2.select_dtypes(include = ['number']).mean()
#same as above
df2.mean(numeric_only=True)

phd            21.52
service        17.60
salary     113789.14
dtype: float64

In [28]:
df.std(numeric_only=True)

phd           12.498425
service       12.139768
salary     28293.661022
dtype: float64

In [29]:
df.phd

0     56
1     12
2     23
3     40
4     20
      ..
73    18
74    19
75    17
76    28
77    23
Name: phd, Length: 78, dtype: int64

In [30]:
df['salary']

0     186960
1      93000
2     110515
3     131205
4     104800
       ...
73    105450
74    104542
75    124312
76    109954
77    109646
Name: salary, Length: 78, dtype: int64

In [31]:
df.phd.head(50).describe()
df.phd.describe()

count    78.000000
mean     19.705128
std      12.498425
min       1.000000
25%      10.250000
50%      18.500000
75%      27.750000
max      56.000000
Name: phd, dtype: float64

In [32]:
df.phd.count()

np.int64(78)

In [33]:
print(df.phd.mean())

19.705128205128204

In [34]:
df.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [35]:
df_rank = df.groupby(['rank'])

In [37]:
df_rank.mean(numeric_only=True)

                 phd    service         salary
rank
AssocProf  15.076923  11.307692   91786.230769
AsstProf    5.052632   2.210526   81362.789474
Prof       27.065217  21.413043  123624.804348

In [38]:
df_rank.describe()

            phd                                                      service  \
          count       mean        std   min    25%   50%   75%   max   count
rank
AssocProf  13.0  15.076923   5.589597   9.0  12.00  13.0  19.0  26.0    13.0
AsstProf   19.0   5.052632   2.738079   1.0   3.50   4.0   7.0  11.0    19.0
Prof       46.0  27.065217  10.185834  12.0  19.25  24.5  34.5  56.0    46.0

                      ...              salary                               \
                mean  ...    75%   max  count           mean           std
rank                  ...
AssocProf  11.307692  ...  11.00  24.0   13.0   91786.230769  18571.183714
AsstProf    2.210526  ...   3.00   6.0   19.0   81362.789474   9381.245301
Prof       21.413043  ...  26.75  51.0   46.0  123624.804348  24850.287853


               min       25%       50%        75%       max
rank
AssocProf  62884.0   74830.0  103613.0  104542.00  119800.0
AsstProf   63100.0   74096.0   78500.0   91150.00   97032.0
Prof       57800.0  105112.5  123321.5  143512.25  186960.0

[3 rows x 24 columns]

In [42]:
df.groupby(['sex']).mean(numeric_only=True)

              phd    service         salary
sex
Female  16.512821  11.564103  101002.410256
Male    22.897436  18.538462  115045.153846

In [44]:
df[df.salary > 120000]

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
3   Prof          A   40       31    Male  131205
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
19  Prof          A   29       27    Male  150500
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
58  Prof          B   36       26  Female  144651
72  Prof          B   24       15  Female  161101
75  Prof          B   17       17  Female  124312

In [45]:
df[df['salary'] <= 120000]

         rank discipline  phd  service     sex  salary
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
4        Prof          B   20       18    Male  104800
6   AssocProf          A   20       17    Male   81285
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
12   AsstProf          B    1        0    Male   88000
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
18       Prof          A   19        7    Male  107300
20   AsstProf          B    4        4    Male   92000
21       Prof          A   33       30    Male  103106
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
28   AsstProf          B    7        2    Male   91300
30  AssocProf          B    9        7    Male  107008
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
37       Prof          A   20        8    Male  102000
38   AsstProf          B    4        3    Male   91000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
50   AsstProf          B   10        5  Female   97032
52       Prof          A   12        0  Female  105000
53   AsstProf          A    5        3  Female   73500
54  AssocProf          A   25       22  Female   62884
55   AsstProf          A    2        0  Female   72500
56  AssocProf          A   10        8  Female   77500
57   AsstProf          A    3        1  Female   72500
59  AssocProf          B   12       10  Female  103994
60   AsstProf          B    3        3  Female   92000
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
66   AsstProf          A    7        6  Female   63100
67       Prof          A   17       11  Female   90450
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [60]:
newDf = df[['salary','rank']]
print(df.iloc[:,2])

0     56
1     12
2     23
3     40
4     20
      ..
73    18
74    19
75    17
76    28
77    23
Name: phd, Length: 78, dtype: int64

In [61]:
df.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [65]:
df.iloc[0:,[1,3]]

   discipline  service
0           B       49
1           A        6
2           A       20
3           A       31
4           B       18
..        ...      ...
73          B       10
74          B        6
75          B       17
76          A       14
77          A       15

[78 rows x 2 columns]

In [67]:
df.iloc[1:11, 1:4]

   discipline  phd  service
1           A   12        6
2           A   23       20
3           A   40       31
4           B   20       18
5           A   20       20
6           A   20       17
7           A   18       18
8           A   29       19
9           A   51       51
10          B   39       33

In [68]:
df.iloc[:,5:]

    salary
0   186960
1    93000
2   110515
3   131205
4   104800
..     ...
73  105450
74  104542
75  124312
76  109954
77  109646

[78 rows x 1 columns]

In [72]:
df.iloc[[60,] ,]

        rank discipline  phd  service     sex  salary
60  AsstProf          B    3        3  Female   92000

In [73]:
df.iloc[[1,3] ,]

   rank discipline  phd  service   sex  salary
1  Prof          A   12        6  Male   93000
3  Prof          A   40       31  Male  131205